# Generated by Django 3.0.1 on 2019-12-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
